In [36]:
!pip install mysql-connector-python
!pip install sqlalchemy
#!pip install urllib

Requirement already satisfied: mysql-connector-python in ./opt/anaconda3/lib/python3.9/site-packages (8.0.32)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in ./opt/anaconda3/lib/python3.9/site-packages (from mysql-connector-python) (3.20.3)
Requirement already satisfied: sqlalchemy in ./opt/anaconda3/lib/python3.9/site-packages (1.4.39)
Requirement already satisfied: greenlet!=0.4.17 in ./opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy) (1.1.1)

In [39]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine
from urllib import request
from urllib.parse import quote_plus

In [40]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="root@123",
  database="data_lake"
)

In [41]:
engine = create_engine('mysql+mysqlconnector://root:%s@localhost/data_lake' % quote_plus("root@123"))

In [23]:
# Read the CSV file into a pandas DataFrame
df = pd.read_csv("data_lake.csv")

/var/folders/sr/vhwd_mss0r9616ls0k3q7zbh0000gn/T/ipykernel_67542/912998377.py:2: DtypeWarning: Columns (3,4,6,7,8,9,10,11,15,16,17,18,21,22,24,25,27,28,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data_lake.csv")

In [24]:
# Slice the data by selecting a subset of columns and/or rows
subset = df.loc[29292:30584, ['ranks', 'title', 'no_of_reviews', 'ratings', 'author', 'cover_type', 'year','genre', 'price']]

In [4]:
subset.shape

(1293, 9)

In [5]:
subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1293 entries, 29292 to 30584
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ranks          1287 non-null   float64
 1   title          1286 non-null   object
 2   no_of_reviews  1287 non-null   object
 3   ratings        1287 non-null   float64
 4   author         1286 non-null   object
 5   cover_type     1286 non-null   object
 6   year           1291 non-null   float64
 7   genre          1288 non-null   object
 8   price          1287 non-null   float64
dtypes: float64(4), object(5)
memory usage: 91.0+ KB

In [6]:
# Check for missing values in each column
subset.isnull().sum()

ranks            6
title            7
no_of_reviews    6
ratings          6
author           7
cover_type       7
year             2
genre            5
price            6
dtype: int64

In [7]:
# Drop rows with missing values
subset = subset.dropna()
subset

,ranks,title,no_of_reviews,ratings,author,cover_type,year,genre,price
29292,1.0,The Lost Symbol,"16,118",4.4,Dan Brown,Hardcover,2009.0,Fiction,12.49
29293,2.0,The Shack: Where Tragedy Confronts Eternity,"23,392",4.7,William P. Young,Paperback,2009.0,Fiction,13.40
29294,3.0,Liberty and Tyranny: A Conservative Manifesto,"5,036",4.8,Mark R. Levin,Hardcover,2009.0,Non Fiction,9.93
29295,4.0,"Breaking Dawn (The Twilight Saga, Book 4)","16,912",4.7,Stephenie Meyer,Hardcover,2009.0,Fiction,14.30
29296,5.0,Going Rogue: An American Life,"1,572",4.6,Sarah Palin,Hardcover,2009.0,Non Fiction,9.99
...,...,...,...,...,...,...,...,...,...
30578,96.0,Will,"21,401",4.8,Will Smith,Hardcover,2021.0,Non Fiction,16.69
30579,97.0,Think and Grow Rich: The Landmark Bestseller N...,"79,872",4.7,Napoleon Hill,Paperback,2021.0,Non Fiction,7.49
30580,98.0,Dragons Love Tacos,"15,753",4.8,Adam Rubin,Hardcover,2021.0,Fiction,8.95
30581,99.0,The Truth About COVID-19: Exposing The Great R...,"7,246",4.8,Doctor Joseph Mercola,Hardcover,2021.0,Non Fiction,7.59
30582,100.0,First Little Readers Parent Pack: Guided Readi...,"27,332",4.7,Deborah Schecter,Paperback,2021.0,Non Fiction,13.29

In [8]:
# use reindex to change the order of columns
subset = subset.reindex(columns=["ranks","title","no_of_reviews","ratings","author", "year","price", "genre", "cover_type"])
subset

,ranks,title,no_of_reviews,ratings,author,year,price,genre,cover_type
29292,1.0,The Lost Symbol,"16,118",4.4,Dan Brown,2009.0,12.49,Fiction,Hardcover
29293,2.0,The Shack: Where Tragedy Confronts Eternity,"23,392",4.7,William P. Young,2009.0,13.40,Fiction,Paperback
29294,3.0,Liberty and Tyranny: A Conservative Manifesto,"5,036",4.8,Mark R. Levin,2009.0,9.93,Non Fiction,Hardcover
29295,4.0,"Breaking Dawn (The Twilight Saga, Book 4)","16,912",4.7,Stephenie Meyer,2009.0,14.30,Fiction,Hardcover
29296,5.0,Going Rogue: An American Life,"1,572",4.6,Sarah Palin,2009.0,9.99,Non Fiction,Hardcover
...,...,...,...,...,...,...,...,...,...
30578,96.0,Will,"21,401",4.8,Will Smith,2021.0,16.69,Non Fiction,Hardcover
30579,97.0,Think and Grow Rich: The Landmark Bestseller N...,"79,872",4.7,Napoleon Hill,2021.0,7.49,Non Fiction,Paperback
30580,98.0,Dragons Love Tacos,"15,753",4.8,Adam Rubin,2021.0,8.95,Fiction,Hardcover
30581,99.0,The Truth About COVID-19: Exposing The Great R...,"7,246",4.8,Doctor Joseph Mercola,2021.0,7.59,Non Fiction,Hardcover
30582,100.0,First Little Readers Parent Pack: Guided Readi...,"27,332",4.7,Deborah Schecter,2021.0,13.29,Non Fiction,Paperback

In [9]:
subset = pd.DataFrame(subset)
subset.columns = ["book_rank", "book_title", "no_of_reviews", "rating","authors", "year", "price", "genre", "cover_type"]

subset

,book_rank,book_title,no_of_reviews,rating,authors,year,price,genre,cover_type
29292,1.0,The Lost Symbol,"16,118",4.4,Dan Brown,2009.0,12.49,Fiction,Hardcover
29293,2.0,The Shack: Where Tragedy Confronts Eternity,"23,392",4.7,William P. Young,2009.0,13.40,Fiction,Paperback
29294,3.0,Liberty and Tyranny: A Conservative Manifesto,"5,036",4.8,Mark R. Levin,2009.0,9.93,Non Fiction,Hardcover
29295,4.0,"Breaking Dawn (The Twilight Saga, Book 4)","16,912",4.7,Stephenie Meyer,2009.0,14.30,Fiction,Hardcover
29296,5.0,Going Rogue: An American Life,"1,572",4.6,Sarah Palin,2009.0,9.99,Non Fiction,Hardcover
...,...,...,...,...,...,...,...,...,...
30578,96.0,Will,"21,401",4.8,Will Smith,2021.0,16.69,Non Fiction,Hardcover
30579,97.0,Think and Grow Rich: The Landmark Bestseller N...,"79,872",4.7,Napoleon Hill,2021.0,7.49,Non Fiction,Paperback
30580,98.0,Dragons Love Tacos,"15,753",4.8,Adam Rubin,2021.0,8.95,Fiction,Hardcover
30581,99.0,The Truth About COVID-19: Exposing The Great R...,"7,246",4.8,Doctor Joseph Mercola,2021.0,7.59,Non Fiction,Hardcover
30582,100.0,First Little Readers Parent Pack: Guided Readi...,"27,332",4.7,Deborah Schecter,2021.0,13.29,Non Fiction,Paperback

In [10]:
# Set the index of the DataFrame to a sequence of integers
subset.reset_index(drop=True, inplace=True)

subset

,book_rank,book_title,no_of_reviews,rating,authors,year,price,genre,cover_type
0,1.0,The Lost Symbol,"16,118",4.4,Dan Brown,2009.0,12.49,Fiction,Hardcover
1,2.0,The Shack: Where Tragedy Confronts Eternity,"23,392",4.7,William P. Young,2009.0,13.40,Fiction,Paperback
2,3.0,Liberty and Tyranny: A Conservative Manifesto,"5,036",4.8,Mark R. Levin,2009.0,9.93,Non Fiction,Hardcover
3,4.0,"Breaking Dawn (The Twilight Saga, Book 4)","16,912",4.7,Stephenie Meyer,2009.0,14.30,Fiction,Hardcover
4,5.0,Going Rogue: An American Life,"1,572",4.6,Sarah Palin,2009.0,9.99,Non Fiction,Hardcover
...,...,...,...,...,...,...,...,...,...
1280,96.0,Will,"21,401",4.8,Will Smith,2021.0,16.69,Non Fiction,Hardcover
1281,97.0,Think and Grow Rich: The Landmark Bestseller N...,"79,872",4.7,Napoleon Hill,2021.0,7.49,Non Fiction,Paperback
1282,98.0,Dragons Love Tacos,"15,753",4.8,Adam Rubin,2021.0,8.95,Fiction,Hardcover
1283,99.0,The Truth About COVID-19: Exposing The Great R...,"7,246",4.8,Doctor Joseph Mercola,2021.0,7.59,Non Fiction,Hardcover
1284,100.0,First Little Readers Parent Pack: Guided Readi...,"27,332",4.7,Deborah Schecter,2021.0,13.29,Non Fiction,Paperback

In [11]:
# check for null values in the 'price' column
null_values = subset['price'].isnull().sum()

print("The 'price' column has", null_values, "null values.")

The 'price' column has 0 null values.

In [12]:
# Replace NaN values with 0
subset['year'] = subset['year'].fillna(0)

# Convert column to integers
subset['year'] = subset['year'].astype(int)

subset

,book_rank,book_title,no_of_reviews,rating,authors,year,price,genre,cover_type
0,1.0,The Lost Symbol,"16,118",4.4,Dan Brown,2009,12.49,Fiction,Hardcover
1,2.0,The Shack: Where Tragedy Confronts Eternity,"23,392",4.7,William P. Young,2009,13.40,Fiction,Paperback
2,3.0,Liberty and Tyranny: A Conservative Manifesto,"5,036",4.8,Mark R. Levin,2009,9.93,Non Fiction,Hardcover
3,4.0,"Breaking Dawn (The Twilight Saga, Book 4)","16,912",4.7,Stephenie Meyer,2009,14.30,Fiction,Hardcover
4,5.0,Going Rogue: An American Life,"1,572",4.6,Sarah Palin,2009,9.99,Non Fiction,Hardcover
...,...,...,...,...,...,...,...,...,...
1280,96.0,Will,"21,401",4.8,Will Smith,2021,16.69,Non Fiction,Hardcover
1281,97.0,Think and Grow Rich: The Landmark Bestseller N...,"79,872",4.7,Napoleon Hill,2021,7.49,Non Fiction,Paperback
1282,98.0,Dragons Love Tacos,"15,753",4.8,Adam Rubin,2021,8.95,Fiction,Hardcover
1283,99.0,The Truth About COVID-19: Exposing The Great R...,"7,246",4.8,Doctor Joseph Mercola,2021,7.59,Non Fiction,Hardcover
1284,100.0,First Little Readers Parent Pack: Guided Readi...,"27,332",4.7,Deborah Schecter,2021,13.29,Non Fiction,Paperback

In [15]:
# Replace NaN values with 0
subset['book_rank'] = subset['book_rank'].fillna(0)

# Convert column to integers
subset['book_rank'] = subset['book_rank'].astype(int)

subset

,book_rank,book_title,no_of_reviews,rating,authors,year,price,genre,cover_type
0,1,The Lost Symbol,"16,118",4.4,Dan Brown,2009,12.49,Fiction,Hardcover
1,2,The Shack: Where Tragedy Confronts Eternity,"23,392",4.7,William P. Young,2009,13.40,Fiction,Paperback
2,3,Liberty and Tyranny: A Conservative Manifesto,"5,036",4.8,Mark R. Levin,2009,9.93,Non Fiction,Hardcover
3,4,"Breaking Dawn (The Twilight Saga, Book 4)","16,912",4.7,Stephenie Meyer,2009,14.30,Fiction,Hardcover
4,5,Going Rogue: An American Life,"1,572",4.6,Sarah Palin,2009,9.99,Non Fiction,Hardcover
...,...,...,...,...,...,...,...,...,...
1280,96,Will,"21,401",4.8,Will Smith,2021,16.69,Non Fiction,Hardcover
1281,97,Think and Grow Rich: The Landmark Bestseller N...,"79,872",4.7,Napoleon Hill,2021,7.49,Non Fiction,Paperback
1282,98,Dragons Love Tacos,"15,753",4.8,Adam Rubin,2021,8.95,Fiction,Hardcover
1283,99,The Truth About COVID-19: Exposing The Great R...,"7,246",4.8,Doctor Joseph Mercola,2021,7.59,Non Fiction,Hardcover
1284,100,First Little Readers Parent Pack: Guided Readi...,"27,332",4.7,Deborah Schecter,2021,13.29,Non Fiction,Paperback

In [45]:

#subset.to_sql(name='books', con=mydb, if_exists='replace', index=False)
subset.to_sql("books", con = engine, if_exists= 'replace', index=False )

-1